import { generateWithProvider } from "@/lib/ai/providers/registry"

export interface AIProviderResult {
  success: boolean
  content: string
  error?: string
  provider?: string
}

const LOCAL_ENGINE_PREFIX = "[Local Engine] "

export async function generateContent(
  prompt: string,
  toolSlug: string = "ai-writer",
  options?: Record<string, unknown>
): Promise<AIProviderResult> {
  try {
    const result = await generateWithProvider(toolSlug, prompt, options)

    if (result.success && result.content) {
      return {
        success: true,
        content: result.content,
        provider: "gemini",
      }
    }

    return {
      success: true,
      content: `${LOCAL_ENGINE_PREFIX}${generateLocalContent(prompt, options)}`,
      provider: "local",
    }
  } catch {
    return {
      success: true,
      content: `${LOCAL_ENGINE_PREFIX}${generateLocalContent(prompt, options)}`,
      provider: "local",
    }
  }
}

export function isGeminiAvailable(): boolean {
  return !!(
    typeof process !== "undefined" &&
    process.env.GEMINI_API_KEY
  )
}

function generateLocalContent(prompt: string, options?: Record<string, unknown>): string {
  const topic = extractTopic(prompt)
  const wordCount = (options?.wordCount as number) || 500
  const sections = Math.max(3, Math.floor(wordCount / 150))

  const headings = [
    "Introduction",
    ...Array.from({ length: sections - 2 }, (_, i) => `Key Aspect ${i + 1}`),
    "Conclusion",
  ]

  let content = `# ${topic}\n\n`
  for (const heading of headings) {
    if (heading === "Introduction") {
      content += `## ${heading}\n\n${topic} is an important topic that deserves comprehensive coverage. This article explores the key aspects, benefits, and best practices to help you understand and implement effective strategies.\n\n`
    } else if (heading === "Conclusion") {
      content += `## ${heading}\n\nIn conclusion, ${topic.toLowerCase()} offers significant value when properly understood and applied. By following the strategies outlined in this article, you can achieve better results and stay ahead of the curve.\n\n`
    } else {
      content += `## ${heading}\n\nWhen it comes to ${topic.toLowerCase()}, there are several important factors to consider. Understanding these elements will help you make more informed decisions and optimize your approach for maximum impact.\n\n`
      content += `Key points to consider include:\n- Strategic planning and execution\n- Regular monitoring and optimization\n- Staying updated with industry trends\n- Leveraging data-driven insights\n\n`
    }
  }

  content += `## Frequently Asked Questions\n\n`
  content += `### What is ${topic}?\n${topic} refers to the practice of implementing strategic approaches to achieve specific goals.\n\n`
  content += `### Why is ${topic} important?\nUnderstanding ${topic.toLowerCase()} is crucial for staying competitive and achieving sustainable growth.\n\n`

  content += `\n---\n\n`
  content += `*This content was generated by the Local Engine. The Gemini API key was not available. Set the GEMINI_API_KEY environment variable for premium AI-generated content.*`

  return content
}

function extractTopic(prompt: string): string {
  const topicMatch = prompt.match(/about ["""]?([^""\n]+)["""]?/i)
  if (topicMatch) return topicMatch[1].trim()
  const lines = prompt.split("\n").filter(l => l.trim())
  const topicLine = lines.find(l => l.includes('"'))
  if (topicLine) {
    const m = topicLine.match(/["""]([^""]+)["""]/)
    if (m) return m[1].trim()
  }
  return "Generated Article"
}
